#ifndef STM32F4XX_HAL_CONF_H
#define STM32F4XX_HAL_CONF_H

#define HAL_MODULE_ENABLED
#define HAL_FLASH_MODULE_ENABLED

#define HSE_VALUE 8000000u
#define HSE_STARTUP_TIMEOUT 100u
#define HSI_VALUE 16000000u
#define LSI_VALUE 32000u
#define LSE_VALUE 32768u
#define LSE_STARTUP_TIMEOUT 5000u
#define EXTERNAL_CLOCK_VALUE 12288000u

#define VDD_VALUE 3300u
#define TICK_INT_PRIORITY 0x0Fu
#define USE_RTOS 0u
#define PREFETCH_ENABLE 1u
#define INSTRUCTION_CACHE_ENABLE 1u
#define DATA_CACHE_ENABLE 1u

#define USE_HAL_ADC_REGISTER_CALLBACKS 0u
#define USE_HAL_CAN_REGISTER_CALLBACKS 0u
#define USE_HAL_CEC_REGISTER_CALLBACKS 0u
#define USE_HAL_CRYP_REGISTER_CALLBACKS 0u
#define USE_HAL_DAC_REGISTER_CALLBACKS 0u
#define USE_HAL_DCMI_REGISTER_CALLBACKS 0u
#define USE_HAL_DFSDM_REGISTER_CALLBACKS 0u
#define USE_HAL_DMA2D_REGISTER_CALLBACKS 0u
#define USE_HAL_DSI_REGISTER_CALLBACKS 0u
#define USE_HAL_ETH_REGISTER_CALLBACKS 0u
#define USE_HAL_HASH_REGISTER_CALLBACKS 0u
#define USE_HAL_HCD_REGISTER_CALLBACKS 0u
#define USE_HAL_I2C_REGISTER_CALLBACKS 0u
#define USE_HAL_FMPI2C_REGISTER_CALLBACKS 0u
#define USE_HAL_I2S_REGISTER_CALLBACKS 0u
#define USE_HAL_IRDA_REGISTER_CALLBACKS 0u
#define USE_HAL_LPTIM_REGISTER_CALLBACKS 0u
#define USE_HAL_LTDC_REGISTER_CALLBACKS 0u
#define USE_HAL_MMC_REGISTER_CALLBACKS 0u
#define USE_HAL_NAND_REGISTER_CALLBACKS 0u
#define USE_HAL_NOR_REGISTER_CALLBACKS 0u
#define USE_HAL_PCCARD_REGISTER_CALLBACKS 0u
#define USE_HAL_PCD_REGISTER_CALLBACKS 0u
#define USE_HAL_QSPI_REGISTER_CALLBACKS 0u
#define USE_HAL_RNG_REGISTER_CALLBACKS 0u
#define USE_HAL_RTC_REGISTER_CALLBACKS 0u
#define USE_HAL_SAI_REGISTER_CALLBACKS 0u
#define USE_HAL_SD_REGISTER_CALLBACKS 0u
#define USE_HAL_SMARTCARD_REGISTER_CALLBACKS 0u
#define USE_HAL_SDRAM_REGISTER_CALLBACKS 0u
#define USE_HAL_SRAM_REGISTER_CALLBACKS 0u
#define USE_HAL_SPDIFRX_REGISTER_CALLBACKS 0u
#define USE_HAL_SMBUS_REGISTER_CALLBACKS 0u
#define USE_HAL_SPI_REGISTER_CALLBACKS 0u
#define USE_HAL_TIM_REGISTER_CALLBACKS 0u
#define USE_HAL_UART_REGISTER_CALLBACKS 0u
#define USE_HAL_USART_REGISTER_CALLBACKS 0u
#define USE_HAL_WWDG_REGISTER_CALLBACKS 0u

#include "stm32f4xx_hal_flash.h"

#define assert_param(expr) ((void)0u)

#endif
